### PR TITLE
fix: exclude hidden type inputs from focusable selector

### LINKED ISSUE #466: userEvent.tab tries to focus <input type="hidden" />, preventing active element from changing
- `@testing-library/user-event` version: 12.1.7

- Testing Framework and version: jest@26.5.2
  
- DOM Environment: jsdom@16.4.0
  

Relevant code or config

```javascript
test('repro', () => {
    const input = document.createElement('input');
    input.type = 'hidden';
    document.body.appendChild(input);

    const div = document.createElement('div');
    div.tabIndex = 0;
    document.body.appendChild(div);

    expect(document.activeElement).toBe(document.body);

    // This attempts to focus <input type="hidden /> so active element doesn't change
    userEvent.tab();

    // Error since active element is still document.body
    expect(document.activeElement).toBe(div);
});
```

What you did: `jest`

What happened:
```js
    expect(received).toBe(expected) // Object.is equality

    expect(received).toBe(expected) // Object.is equality

    - Expected  - 0
    + Received  + 5

    + <body>
    +   <input
    +     type="hidden"
    +   />
        <div
          tabindex="0"
        />
    + </body>
```

Problem description: Hidden-type input elements do not receive tab focus in common browsers, but `userEvent.tab` fails to exclude them from its tab-able element list which produces incorrect behavior.

Suggested solution: Change `input:not([disabled])` to `input:not([type=hidden]):not([disabled])` in `FOCUSABLE_SELECTOR` in `src/utils.js`

### PR DESCRIPTION
**Pull request by lazytype**
fix #466 

**What**: `tab` attempts to focus hidden type inputs

**Why**: Hidden-type input elements do not receive tab focus in common browsers, but `tab` fails to exclude them from its tab-able element list which produces incorrect behavior.

**How**: Update `FOCUSABLE_SELECTOR` to exclude hidden inputs.

**Checklist**:

- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

File: src/__tests__/tab.js [hunk 1]
```diff
@@ -287,6 +287,25 @@ test('should not tab to <a> with no href', () => {
...
 
+test('should not tab to <input> with type="hidden"', () => {
+  setup(`
+    <div>
+      <input data-testid="element" tabIndex="0" type="checkbox" />
+      <input type="hidden">
+      <input data-testid="element" type="text"  />
+    </div>`)
+
+  const [checkbox, text] = document.querySelectorAll('[data-testid="element"]')
```
Comment (ph-fritsche) [inline src/__tests__/tab.js:298]: We can keep the code leaner here:
```js
const {elements: [checkbox,, text]} = setup(`
  <input type="checkbox" />
  <input type="hidden" />
  <input type="text"  />
`)
```

**Review by ph-fritsche — CHANGES_REQUESTED** [review]
Thank you for the report and quick fix. :)

File: src/utils.js [hunk 2]
```diff
@@ -219,7 +219,7 @@ function setSelectionRangeIfNecessary(
 }
 
 const FOCUSABLE_SELECTOR = [
-  'input:not([disabled])',
+  'input:not([type=hidden]):not([disabled])',
```
Comment (kentcdodds) [inline src/utils.js:222]: Actually, the hidden attribute could be applied to any element. I think we need to add this to all of the selectors here.

**Review by kentcdodds — COMMENTED** [review]
Thanks! One thing.

File: src/utils.js (hunk 2 above)
Comment (ph-fritsche) [reply src/utils.js:222]: I just checked in Chrome: `<div tabIndex="0" type="hidden">` has no effect.
I don't think it is specified to have any meaning on other elements.

Comment (kentcdodds) [reply src/utils.js:222]: Oh, duh. I was thinking about the `hidden` attribute itself (like `<button hidden="true">`).

But yeah, the `hidden` type is what we're dealing with here and that works fine. Thanks!

I wonder whether we should/need to fix how we handle the hidden attribute though 🤔

I'll merge this as-is. Thanks!

Comment (kentcdodds) [reply src/utils.js:222]: @lazytype, I mean, I'm happy to merge after you sort out @ph-fritsche's comment https://github.com/testing-library/user-event/pull/467/files#r504487490

**Review by kentcdodds — APPROVED** [review]
Solid, thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @lazytype for code and tests
