### PR TITLE
fix: convert exported modules to typescript

### LINKED ISSUE #594: Click, keyboard & type TypeScript types are resolved as "any" because of wrong imports in typings
- `@testing-library/dom` version: 7.30.0
- `@testing-library/user-event` version: 13.0.1
- `typescript` version: 4.2.3

**Problem description:**
The file `typings/index.d.ts` contains type imports from `../src/` folder, which does not exist in the distributed package, so all those types are resolved to `any`.

Codesandbox: https://codesandbox.io/s/romantic-shadow-uio28

image

`typings/index.d.ts` in the corresponding `node_modules` folder:

image

This concerns the following types:

- click, clickOptions
- keyboard, keyboardOptions, keyboardKey,
- type, typeOptions

### LINKED ISSUE #598: Typescript error in click function when upgrading to v13.0.3
- `@testing-library/user-event` version: 13.0.3

- Testing Framework and version: jest@26.6.0
  
- DOM Environment:
-  "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.5",
  

What you did: Upgrading to v13.0.3 the types exported seem to have the `init` property of the click function as mandatory while in `click.d.ts` [in the repo](https://github.com/testing-library/user-event/blob/16314c6f10a4e0cdd25024e25ebb588c7abe8935/src/click.d.ts) it seems to be optional.

What happened: Typescript error. 

image
image

### PR DESCRIPTION
**Pull request by ph-fritsche**
**What**:

Converted all exported modules to Typescript.
Fixed some bugs / false assumptions along the way.
Added more TODOs to verify previous implementations.

**Why**:

Closes #598 
Closes #594 (hopefully this time for good)

**Checklist**:

- N/A Documentation
- [x] Tests
- N/A Typings
- [x] Ready to be merged

### CODE REVIEW

File: src/paste.ts [hunk 1]
```diff
@@ -3,15 +3,25 @@ import {
...
+  initialSelectionStart?: number
+  initialSelectionEnd?: number
+}
+
 function paste(
-  element,
-  text,
-  init,
-  {initialSelectionStart, initialSelectionEnd} = {},
+  element: HTMLInputElement | HTMLTextAreaElement,
```
Comment (GreenGremlin) [inline src/paste.ts:15]: This type definition makes it impossible to use elements returned by RTS queries, without type casting.

see: https://github.com/testing-library/user-event/issues/648

Comment (GreenGremlin) [reply src/paste.ts:15]: Here's a PR to fix this: https://github.com/testing-library/user-event/pull/649
