### PR TITLE
fix(tab): tab order on radio and tabindex=-1

### LINKED ISSUE #441: cannot tab back to previuos element when focus is on radiogroup
Since 11.3.2 it is not possible to tab back to the previous element when focus is on a radiogroup.
The focus is then instead switched to the last accessible element.

I wrote a little test scenario where the problem is shown:
https://codesandbox.io/s/distracted-beaver-zwbh2

### PR DESCRIPTION
**Pull request by ph-fritsche**
fix #441 
replaces #443 

**What**:

`tab()` did not produce the same tab order as the browser does.

**How**:

Reimplemented how the tab sequence is determined.
* Never dismiss activeElement for tab sequence
* Keep DOM order (ignore tabindex) if activeElement has `tabindex="-1"`
* Reimplemented which radio elements to prune from tab order:
   * For radio groups keep only the active radio
   * If there is no active radio, keep only the checked radio

**Checklist**:
* [x] Tests
* [x] Ready to be merged

### CODE REVIEW

**Review by marcosvega91 — CHANGES_REQUESTED** [review]
Hi @ph-fritsche thanks a lot for this 😄 

Do you wanna work to add some tests to make the coverage 100% ?

**Review by marcosvega91 — APPROVED** [review]
thanks a lot for this 🥳  . For me is ready

File: src/__tests__/tab.js [hunk 1]
```diff
@@ -244,6 +244,26 @@ test('should suport a mix of elements with/without tab index', () => {
...
 })
 
+test('ignore tabindex when active element has tabindex="-1"', () => {
+  setup(`
+    <input tabindex='1'/>
+    <input tabindex='0'/>
+    <input tabindex='-1'/>
+    <input tabindex='2'/>
+  `)
+  const [inputA, inputB, inputC, inputD] = document.body.lastChild.children
```
Comment (kentcdodds) [inline src/__tests__/tab.js:254]: Rather than using `document.body.lastChild`, could we get that element from `const {element} = setup('...html...')`?

File: src/__tests__/tab.js [hunk 2]
```diff
@@ -388,51 +408,103 @@ test('should keep focus on the document if there are no enabled, focusable eleme
...
+  const [
+    inputA,
+    radioA,
+    radioB,
+    inputB,
+    radioC,
+    radioD,
+    radioE,
+    inputC,
+  ] = document.body.lastChild.children
```
Comment (kentcdodds) [inline src/__tests__/tab.js:431]: Here as well, let's not rely on `document.body.lastChild` anywhere.

File: src/__tests__/tab.js [hunk 3]
```diff
@@ -388,51 +408,103 @@ test('should keep focus on the document if there are no enabled, focusable eleme
...
+  `)
+  const [
+    inputA,
+    ,
+    inputB,
+    radioB,
+    inputC,
+    ,
+    inputD,
+  ] = document.body.lastChild.children
```
Comment (kentcdodds) [inline src/__tests__/tab.js:478]: Here as well.

File: src/__tests__/tab.js [hunk 4]
```diff
@@ -388,51 +408,103 @@ test('should keep focus on the document if there are no enabled, focusable eleme
...
+  setup(`
+    <input/>
+    <input type="radio" name="radio" checked/>
+    <input/>
+    <input type="radio" name="radio"/>
+    <input/>
+  `)
 
-  userEvent.tab({shift: true})
+  const [, , , radioB, inputC] = document.body.lastChild.children
```
Comment (kentcdodds) [inline src/__tests__/tab.js:501]: Here too.

**Review by kentcdodds — COMMENTED** [review]
Looks solid. Just one slight comment.

File: src/__tests__/tab.js (hunk 1 above)
Comment (kentcdodds) [reply src/__tests__/tab.js:254]: Noticed the recent push. Don't miss this one :)

Comment (ph-fritsche) [reply src/__tests__/tab.js:254]: done.

While we're at it:
I think the extra `<div>` in most tests to comply with the implementation of `setup()` is no improvement.

What do you think about rewriting that `setup()` function as:
```js
function setup(ui, {eventHandlers} = {}) {
  const div = document.createElement('div')
  div.innerHTML = ui.trim()
  document.body.append(div)

  return {
    element: div.firstChild,
    elements: div.children,
    ...addListeners(div, {eventHandlers}),
  }
}
```

Comment (kentcdodds) [reply src/__tests__/tab.js:254]: Sure! Let's do that in another PR though. I'll merge this as-is 👍

Comment (kentcdodds) [reply src/__tests__/tab.js:254]: Looks like this line hasn't been updated yet.

**Review by kentcdodds — APPROVED** [review]
Super!

**Comment by kentcdodds** [comment]
@all-contributors please add @ph-fritsche for code and tests
